[package]
name = "defender"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.24.0"
pistoncore-glutin_window = "0.43.0"
piston2d-opengl_graphics = "0.50.0"
rand = "0.4"